#!/bin/sh

echo "Wait i am choosing the random wallpaper"
wall=$(find ~/wallpaper -type f | shuf -n 1)
feh --bg-fill $wall
wal -i $wall >/dev/null
echo "Generating your beautiful olour schemes"
sed -i 'N;$!P;D' ~/.cache/wal/colors-wal-dwm.h
echo 'Recompiling dwm with new colors bitch .....'
(cd ~/dwm && sudo make clean install>/dev/null)
echo "Finished please restart"





sudo pacman -S --noconfirm xorg gdm gnome gnome-extra firefox gnome-tweaks simplescreenrecorder arc-gtk-theme arc-icon-theme obs-studio vlc dina-font tamsyn-font bdf-unifont ttf-bitstream-vera ttf-croscore ttf-dejavu ttf-droid gnu-free-fonts ttf-ibm-plex ttf-liberation ttf-linux-libertine noto-fonts ttf-roboto tex-gyre-fonts ttf-ubuntu-font-family ttf-anonymous-pro ttf-cascadia-code ttf-fantasque-sans-mono ttf-fira-mono ttf-hack ttf-fira-code ttf-inconsolata ttf-jetbrains-mono ttf-monofur adobe-source-code-pro-fonts cantarell-fonts inter-font ttf-opensans gentium-plus-font ttf-junicode adobe-source-han-sans-otc-fonts adobe-source-han-serif-otc-fonts noto-fonts-cjk noto-fonts-emoji

